name: Spider Jar Gen CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Build with Gradle
      run: ./gradlew.bat
        
    - name: Upload App To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: com.github.tvbox.osc
        path: ${{ github.workspace }}/apk/*
